### ISSUE TITLE
question about running scripts: time out initializing process group

### ISSUE THREAD

**Issue by boxwayne** [openai/consistency_models#14]
I had downloaded the data set of LSUN bedroom and run the Consistency Training on LSUN-256 command in cm/scripts/launch.sh in terminal. No additional message is showed in the window. The screenshot is attached below:
![Screenshot from 2023-04-17 11-55-09](https://user-images.githubusercontent.com/56670996/232375138-c4dfdfaa-1f50-4a93-91b9-4347e1a8bbbd.png)
Is it normal? Or maybe I need to wait for a long period of time until the training process is finished, and then some messages will show up.

**Comment by boxwayne** [comment]
Finally some errors came. Is there anyone facing the same problem?
![Screenshot from 2023-04-17 12-14-58](https://user-images.githubusercontent.com/56670996/232376776-ba652817-ed24-422e-b466-7350be4006b8.png)
![Screenshot from 2023-04-17 12-15-43](https://user-images.githubusercontent.com/56670996/232376792-1a4a94df-f918-421c-b095-9b6c2f7af497.png)
![Screenshot from 2023-04-17 12-16-12](https://user-images.githubusercontent.com/56670996/232376808-f984876c-5957-49a2-bda3-c53a674d8754.png)

**Comment by aarontan-git** [comment]
what was the problem?

**Comment by maxiuw** [comment]
same here, basically nothing happens. Also no spikes in GPU or CPU memory...
