### ISSUE TITLE
RuntimeError: FlashAttention is only supported on CUDA 11 and above

### ISSUE THREAD

**Issue by zhouzikang** [openai/consistency_models#23]
![Screenshot from 2023-04-24 15-28-06](https://user-images.githubusercontent.com/77162542/233928331-b53fd7c3-1e07-487d-88ab-bf44404b1a7e.png)
Does anyone have the same problem?
Can you help me out? 
I will be very grateful！

**Comment by treefreq** [comment]
别跑了，复现出来也跑不出像他论文里那样的图

**Comment by xiongzhp** [comment]
exactly the same issue

**Comment by zhouzikang** [comment]
> 别跑了，复现出来也跑不出像他论文里那样的图
大佬已经成功复现了吗？能否指点一二？

**Comment by zhouzikang** [comment]
> exactly the same issue

Have you found a solution yet?

**Comment by treefreq** [comment]
> 

都提示了呀，换一个高级CUDA

**Comment by CallShaul** [comment]
Same issue here (Kubuntu 20)

**Comment by haoychen3** [comment]
I solved this problem by:
export PATH=/usr/local/cuda-11.7/bin:$PATH

The cause of this error is probably that the CUDA version of nvcc (obtained by typing "nvcc -V") mismatch your CUDA version for torch (11.7).

Similar issues are solved here: [](https://stackoverflow.com/questions/40517083/multiple-cuda-versions-on-machine-nvcc-v-confusion)

**Comment by zhouzikang** [comment]
> I solved this problem by: export PATH=/usr/local/cuda-11.7/bin:$PATH
> 
> The cause of this error is probably that the CUDA version of nvcc (obtained by typing "nvcc -V", probably < 11.0) mismatches your CUDA version for torch (11.7).
> 
> Similar issues are solved here: https://stackoverflow.com/questions/40517083/multiple-cuda-versions-on-machine-nvcc-v-confusion

Thank you very much! I have solved the problem.
