### ISSUE TITLE
Why use teacher model in Consistency training

### ISSUE THREAD

**Issue by CellNw** [openai/consistency_models#53]
writen In `launch.sh` section "Consistency training on class-conditional ImageNet-64, and LSUN 256"
```
mpiexec -n 8 python cm_train.py --training_mode consistency_training ... --teacher_model_path /path/to/edm_bedroom256_ema.pt ...
```
so,Why use teacher model in Consistency training.In my understanding,Consistency training is training model isolate.
is anything wrong?
here is Consistency Training (CT) Algorithm in paper
![image](https://github.com/openai/consistency_models/assets/24557454/3a7cffdb-11de-4a9b-ab34-ff3acdae6235)

**Comment by dome272** [comment]
It probably was forgotten to take out of the command. Looking at the code, the teacher_model will not be used if the training mode is consistency_training: https://github.com/openai/consistency_models/blob/e32b69ee436d518377db86fb2127a3972d0d8716/cm/train_util.py#L488

Only the model and target model will be passed to the loss calculation https://github.com/openai/consistency_models/blob/e32b69ee436d518377db86fb2127a3972d0d8716/cm/karras_diffusion.py#L106
And I believe target_model is just the ema model of model (?)

**Comment by CellNw** [comment]
> It probably was forgotten to take out of the command. Looking at the code, the teacher_model will not be used if the training mode is consistency_training:
> 
> https://github.com/openai/consistency_models/blob/e32b69ee436d518377db86fb2127a3972d0d8716/cm/train_util.py#L488
> 
> Only the model and target model will be passed to the loss calculation
> 
> https://github.com/openai/consistency_models/blob/e32b69ee436d518377db86fb2127a3972d0d8716/cm/karras_diffusion.py#L106
> 
> 
> And I believe target_model is just the ema model of model (?)

Thanks for the reply, I checked the code you mentioned
https://github.com/openai/consistency_models/blob/e32b69ee436d518377db86fb2127a3972d0d8716/cm/karras_diffusion.py#L106

The euler_solver and henu_solver will pass the teacher_model.
heun_solver:
https://github.com/openai/consistency_models/blob/e32b69ee436d518377db86fb2127a3972d0d8716/cm/karras_diffusion.py#L148
euler_solver:
https://github.com/openai/consistency_models/blob/e32b69ee436d518377db86fb2127a3972d0d8716/cm/karras_diffusion.py#L168

and those solver will be used to gen 'x_t2'.
https://github.com/openai/consistency_models/blob/e32b69ee436d518377db86fb2127a3972d0d8716/cm/karras_diffusion.py#L193-L196

then 'x_t2' will be passed target_model and finally pass to the loss calculation.
https://github.com/openai/consistency_models/blob/e32b69ee436d518377db86fb2127a3972d0d8716/cm/karras_diffusion.py#L199

**Comment by CellNw** [comment]
> It probably was forgotten to take out of the command. Looking at the code, the teacher_model will not be used if the training mode is consistency_training:
> 
> https://github.com/openai/consistency_models/blob/e32b69ee436d518377db86fb2127a3972d0d8716/cm/train_util.py#L488
> 
> Only the model and target model will be passed to the loss calculation
> 
> https://github.com/openai/consistency_models/blob/e32b69ee436d518377db86fb2127a3972d0d8716/cm/karras_diffusion.py#L106
> 
> 
> And I believe target_model is just the ema model of model (?)

Thanks for the reply, I checked the code you mentioned
https://github.com/openai/consistency_models/blob/e32b69ee436d518377db86fb2127a3972d0d8716/cm/karras_diffusion.py#L106

The euler_solver and henu_solver will pass the teacher_model.
heun_solver:
https://github.com/openai/consistency_models/blob/e32b69ee436d518377db86fb2127a3972d0d8716/cm/karras_diffusion.py#L148
euler_solver:
https://github.com/openai/consistency_models/blob/e32b69ee436d518377db86fb2127a3972d0d8716/cm/karras_diffusion.py#L168

and those solver will be used to gen 'x_t2'.
https://github.com/openai/consistency_models/blob/e32b69ee436d518377db86fb2127a3972d0d8716/cm/karras_diffusion.py#L193-L196

then 'x_t2' will be passed target_model and finally pass to the loss calculation.
https://github.com/openai/consistency_models/blob/e32b69ee436d518377db86fb2127a3972d0d8716/cm/karras_diffusion.py#L199

**Comment by ljw919** [comment]
> > It probably was forgotten to take out of the command. Looking at the code, the teacher_model will not be used if the training mode is consistency_training:
> > https://github.com/openai/consistency_models/blob/e32b69ee436d518377db86fb2127a3972d0d8716/cm/train_util.py#L488
> > 
> > Only the model and target model will be passed to the loss calculation
> > https://github.com/openai/consistency_models/blob/e32b69ee436d518377db86fb2127a3972d0d8716/cm/karras_diffusion.py#L106
> > 
> > And I believe target_model is just the ema model of model (?)
> 
> Thanks for the reply, I checked the code you mentioned
> 
> https://github.com/openai/consistency_models/blob/e32b69ee436d518377db86fb2127a3972d0d8716/cm/karras_diffusion.py#L106
> 
> The euler_solver and henu_solver will pass the teacher_model. heun_solver:
> 
> https://github.com/openai/consistency_models/blob/e32b69ee436d518377db86fb2127a3972d0d8716/cm/karras_diffusion.py#L148
> 
> euler_solver:
> 
> https://github.com/openai/consistency_models/blob/e32b69ee436d518377db86fb2127a3972d0d8716/cm/karras_diffusion.py#L168
> 
> and those solver will be used to gen 'x_t2'.
> 
> https://github.com/openai/consistency_models/blob/e32b69ee436d518377db86fb2127a3972d0d8716/cm/karras_diffusion.py#L193-L196
> 
> then 'x_t2' will be passed target_model and finally pass to the loss calculation.
> 
> https://github.com/openai/consistency_models/blob/e32b69ee436d518377db86fb2127a3972d0d8716/cm/karras_diffusion.py#L199

Thank u, so does the consistency training mode need the teacher model path ?

**Comment by ljw919** [comment]
And I also met the "shape mismatch" in the update ema process of the target model, do u know why?

**Comment by CellNw** [comment]
> Thank u, so does the consistency training mode need the teacher model path ?

no,consistency training mode dont't need the teacher model.

**Comment by keylxiao** [comment]
Hello, I would like to ask why it is so written in cm_train.py. I did not find in the launch.sh file that the parameter value of "training_mode" of any command is "progdist". However, the "training_mode" parameter for both the ct and cd methods contains "consistency".

[consistency_models/cm/cm_train.py](https://github.com/openai/consistency_models/blob/main/scripts/cm_train.py#L39-L44)
```python
39|    if args.training_mode == "progdist":
40|        distillation = False
41|    elif "consistency" in args.training_mode:
42|        distillation = True
43|    else:
44|        raise ValueError(f"unknown training mode {args.training_mode}")
```

in launch.sh
```bash
#########################################################################
# Consistency distillation on class-conditional ImageNet-64, and LSUN 256
#########################################################################

## L_CD^N (l2) on ImageNet-64
mpiexec -n 8 python cm_train.py --training_mode consistency_distillation --target_ema_mode fixed --start_ema 0.95 --scale_mode fixed --start_scales 40 --total_training_steps 600000 --loss_norm l2 --lr_anneal_steps 0 --teacher_model_path /path/to/edm_imagenet64_ema.pt --attention_resolutions 32,16,8 --class_cond True --use_scale_shift_norm True --dropout 0.0 --teacher_dropout 0.1 --ema_rate 0.999,0.9999,0.9999432189950708 --global_batch_size 2048 --image_size 64 --lr 0.000008 --num_channels 192 --num_head_channels 64 --num_res_blocks 3 --resblock_updown True --schedule_sampler uniform --use_fp16 True --weight_decay 0.0 --weight_schedule uniform --data_dir /path/to/data

## L_CD^N (LPIPS) on ImageNet-64
mpiexec -n 8 python cm_train.py --training_mode consistency_distillation --target_ema_mode fixed --start_ema 0.95 --scale_mode fixed --start_scales 40 --total_training_steps 600000 --loss_norm lpips --lr_anneal_steps 0 --teacher_model_path /path/to/edm_imagenet64_ema.pt --attention_resolutions 32,16,8 --class_cond True --use_scale_shift_norm True --dropout 0.0 --teacher_dropout 0.1 --ema_rate 0.999,0.9999,0.9999432189950708 --global_batch_size 2048 --image_size 64 --lr 0.000008 --num_channels 192 --num_head_channels 64 --num_res_blocks 3 --resblock_updown True --schedule_sampler uniform --use_fp16 True --weight_decay 0.0 --weight_schedule uniform --data_dir /path/to/data

## L_CD^N (l2) on LSUN 256
mpiexec -n 8 python cm_train.py --training_mode consistency_distillation --sigma_max 80 --sigma_min 0.002 --target_ema_mode fixed --start_ema 0.95 --scale_mode fixed --start_scales 40 --total_training_steps 600000 --loss_norm l2 --lr_anneal_steps 0 --teacher_model_path /path/to/edm_bedroom256_ema.pt --attention_resolutions 32,16,8 --class_cond False --use_scale_shift_norm False --dropout 0.0 --teacher_dropout 0.1 --ema_rate 0.9999,0.99994,0.9999432189950708 --global_batch_size 256 --image_size 256 --lr 0.00001 --num_channels 256 --num_head_channels 64 --num_res_blocks 2 --resblock_updown True --schedule_sampler uniform --use_fp16 True --weight_decay 0.0 --weight_schedule uniform --data_dir /path/to/bedroom256

## L_CD^N (LPIPS) on LSUN 256
mpiexec -n 8 python cm_train.py --training_mode consistency_distillation --sigma_max 80 --sigma_min 0.002 --target_ema_mode fixed --start_ema 0.95 --scale_mode fixed --start_scales 40 --total_training_steps 600000 --loss_norm lpips --lr_anneal_steps 0 --teacher_model_path /path/to/edm_bedroom256_ema.pt --attention_resolutions 32,16,8 --class_cond False --use_scale_shift_norm False --dropout 0.0 --teacher_dropout 0.1 --ema_rate 0.9999,0.99994,0.9999432189950708 --global_batch_size 256 --image_size 256 --lr 0.00001 --num_channels 256 --num_head_channels 64 --num_res_blocks 2 --resblock_updown True --schedule_sampler uniform --use_fp16 True --weight_decay 0.0 --weight_schedule uniform --data_dir /path/to/bedroom256

#########################################################################
# Consistency training on class-conditional ImageNet-64, and LSUN 256
#########################################################################

## L_CT^N on ImageNet-64
mpiexec -n 8 python cm_train.py --training_mode consistency_training --target_ema_mode adaptive --start_ema 0.95 --scale_mode progressive --start_scales 2 --end_scales 200 --total_training_steps 800000 --loss_norm lpips --lr_anneal_steps 0 --teacher_model_path /path/to/edm_imagenet64_ema.pt --attention_resolutions 32,16,8 --class_cond True --use_scale_shift_norm True --dropout 0.0 --teacher_dropout 0.1 --ema_rate 0.999,0.9999,0.9999432189950708 --global_batch_size 2048 --image_size 64 --lr 0.0001 --num_channels 192 --num_head_channels 64 --num_res_blocks 3 --resblock_updown True --schedule_sampler uniform --use_fp16 True --weight_decay 0.0 --weight_schedule uniform --data_dir /path/to/imagenet64

## L_CT^N on LSUN 256
mpiexec -n 8 python cm_train.py --training_mode consistency_training --target_ema_mode adaptive --start_ema 0.95 --scale_mode progressive --start_scales 2 --end_scales 150 --total_training_steps 1000000 --loss_norm lpips --lr_anneal_steps 0 --teacher_model_path /path/to/edm_bedroom256_ema.pt --attention_resolutions 32,16,8 --class_cond False --use_scale_shift_norm False --dropout 0.0 --teacher_dropout 0.1 --ema_rate 0.9999,0.99994,0.9999432189950708 --global_batch_size 256 --image_size 256 --lr 0.00005 --num_channels 256 --num_head_channels 64 --num_res_blocks 2 --resblock_updown True --schedule_sampler uniform --use_fp16 True --weight_decay 0.0 --weight_schedule uniform --data_dir /path/to/bedroom256

```

**Comment by szh404** [comment]
> And I also met the "shape mismatch" in the update ema process of the target model, do u know why?

Have you solved the problem？I also met this error.

**Comment by Godzilla0517** [comment]
> > And I also met the "shape mismatch" in the update ema process of the target model, do u know why?
> 
> Have you solved the problem？I also met this error.

+1
